### ISSUE TITLE
Once caught that particular task never runs again

### ISSUE THREAD

**Issue by krainboltgreene** [catdad/gulp-graceful-error#8]
```
𝑓 npx gulp watch:all
[17:25:30] Using gulpfile ~/Code/krainboltgreene/deushack/gulpfile.js
[17:25:30] Starting 'build:@internal'...
[17:25:30] Starting 'build:styles'...
[17:25:30] Starting 'build:images'...
[17:25:30] Starting 'build:assets'...
[17:25:30] Starting 'build:fonts'...
[17:25:30] Finished 'build:images' after 9.27 ms
[17:25:30] Finished 'build:styles' after 18 ms
[17:25:30] Finished 'build:assets' after 53 ms
[17:25:30] Finished 'build:fonts' after 54 ms
[17:25:30] Starting 'build:client'...
[17:25:31] Finished 'build:@internal' after 1.67 s
[17:25:31] Starting 'build:server'...
[17:25:32] Finished 'build:server' after 598 ms
[17:25:34] client index.js 2.3 MB
[17:25:34] Finished 'build:client' after 4.19 s
[17:25:34] Starting 'watch:all'...
[17:25:34] Finished 'watch:all' after 36 ms
```

Here we see the `build:client` task running successfully.

Now we add a syntax error:

```
[17:26:03] Starting 'build:styles'...
[17:26:03] Starting 'build:images'...
[17:26:03] Starting 'build:assets'...
[17:26:03] Starting 'build:fonts'...
[17:26:03] Finished 'build:images' after 8.75 ms
[17:26:03] Finished 'build:styles' after 20 ms
[17:26:03] Finished 'build:assets' after 17 ms
[17:26:03] Finished 'build:fonts' after 19 ms
[17:26:03] Starting 'build:client'...
{ SyntaxError: /Users/krainboltgreene/Code/krainboltgreene/deushack/source/client/application/index.js: Invalid left-hand side in assignment expression (22:14)
  20 |   )
  21 |
> 22 |   const DOM = mapValues(infuse(shell()))(state)=.debug()
     |               ^
  23 |
  24 |   DOM.setDebugListener(console.log.bind(console))
  25 |
    at Parser.pp$5.raise (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$2.toAssignable (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:3008:16)
    at Parser.pp$3.parseMaybeAssign (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:3349:45)
    at Parser.pp$1.parseVar (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:2340:24)
    at Parser.pp$1.parseVarStatement (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:2169:8)
    at Parser.pp$1.parseStatement (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:1861:19)
    at Parser.pp$1.parseBlockBody (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$1.parseFunction (/Users/krainboltgreene/Code/krainboltgreene/deushack/node_modules/babylon/lib/index.js:2386:8)
...
```

And when the syntax error is fixed?

```
[17:26:54] Starting 'build:styles'...
[17:26:54] Starting 'build:images'...
[17:26:54] Starting 'build:assets'...
[17:26:54] Starting 'build:fonts'...
[17:26:54] Finished 'build:images' after 3.7 ms
[17:26:54] Finished 'build:styles' after 7.6 ms
[17:26:54] Finished 'build:assets' after 8.11 ms
[17:26:54] Finished 'build:fonts' after 7.89 ms
```

**Comment by catdad** [comment]
Sorry for the delay, I somehow missed this one.

I can't get this to repro. Can you post a minimal gulpfile that is able to reproduce this. For reference, I used the file below:

```javascript
var gulp = require('gulp');
var graceful = require('gulp-graceful-error');
var through = require('through2');

function errStream() {
  return through.obj(function (file, enc, cb) {
    cb(new Error('pineapples'));
  });
}

gulp.task('default', function () {
  return gulp.src('package.json')
    .pipe(graceful())
    .pipe(errStream())
    .graceful();
});

gulp.task('watch', function () {
  gulp.watch('*.json', ['default']);
});
```

I changes package.json several times, and got this output:

```
[23:14:29] Using gulpfile ~\Desktop\graceful-test\gulpfile.js
[23:14:29] Starting 'watch'...
[23:14:29] Finished 'watch' after 9.81 ms
[23:14:40] Starting 'default'...
[23:14:40] Error in plugin 'graceful-gulp'
Message:
    pineapples
[23:14:40] Finished 'default' after 45 ms
[23:14:47] Starting 'default'...
[23:14:47] Error in plugin 'graceful-gulp'
Message:
    pineapples
[23:14:47] Finished 'default' after 11 ms
[23:14:54] Starting 'default'...
[23:14:54] Error in plugin 'graceful-gulp'
Message:
    pineapples
[23:14:54] Finished 'default' after 2.92 ms
[23:14:55] Starting 'default'...
[23:14:55] Error in plugin 'graceful-gulp'
Message:
    pineapples
[23:14:55] Finished 'default' after 11 ms
```

You can see that the `default` task ran each time, as triggered by the `watch` task.
